Fix tests: add project to BQ dataset, fix nanos for mock obj.
* With last commit, BQ path needs to be fully qualified with project name.
* Tests were failing with error: "Mock object has no attribute 'nanos'".
  This is due to instance attributes set in __init__().  See
  https://stackoverflow.com/q/31709792.